#!/usr/bin/env bash
# Discovers registered repos on disk and writes resolved paths to:
#   ~/.claude/project-repos.env   (shell variables, sourced by hooks)
#   ~/.claude/project-repos.json  (JSON, read by Claude for path resolution)
#
# Discovery strategy:
#   1. Honour per-repo overrides in ~/.claude/project-repos.local.env
#   2. Honour PROJECT_REPOS_DIR env var (explicit override of primary search dir)
#   3. Search common parent directories for matching repo names
#   4. Optionally --deep-scan to find repos by git remote (after renames)
#
# Usage:
#   ./discover-repos.sh                          # normal discovery
#   ./discover-repos.sh --deep-scan              # also scan git remotes (slower)
#   ./discover-repos.sh --search-dir /path       # additional search dir
#
# Env vars honoured:
#   PROJECT_REPOS_DIR       primary search dir
#   GITHUB_OWNER            default GitHub owner/org for the project registry

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLKIT_DIR="$(dirname "$SCRIPT_DIR")"
CLAUDE_DIR="$HOME/.claude"
REPOS_CONF="$TOOLKIT_DIR/repos.conf"
ENV_FILE="$CLAUDE_DIR/project-repos.env"
JSON_FILE="$CLAUDE_DIR/project-repos.json"
LOCAL_OVERRIDES="$CLAUDE_DIR/project-repos.local.env"

GITHUB_OWNER_DEFAULT="${GITHUB_OWNER:-my-org}"

DEEP_SCAN=false
EXTRA_SEARCH_DIRS=""

# --- args ---
while [ $# -gt 0 ]; do
  case "$1" in
    --deep-scan) DEEP_SCAN=true; shift ;;
    --search-dir) EXTRA_SEARCH_DIRS="$EXTRA_SEARCH_DIRS $2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# --- search paths (checked in order) ---
SEARCH_PATHS="$HOME"
for dir in code Code projects Projects src dev repos work workspace git; do
  SEARCH_PATHS="$SEARCH_PATHS $HOME/$dir"
done

if [ -n "${PROJECT_REPOS_DIR:-}" ]; then
  SEARCH_PATHS="$PROJECT_REPOS_DIR $SEARCH_PATHS"
fi

if [ -n "$EXTRA_SEARCH_DIRS" ]; then
  SEARCH_PATHS="$EXTRA_SEARCH_DIRS $SEARCH_PATHS"
fi

# ghq support
if command -v ghq >/dev/null 2>&1; then
  GHQ_ROOT=$(ghq root 2>/dev/null || true)
  if [ -n "$GHQ_ROOT" ]; then
    SEARCH_PATHS="$SEARCH_PATHS $GHQ_ROOT $GHQ_ROOT/github.com/$GITHUB_OWNER_DEFAULT"
  fi
fi

# --- overrides ---
get_local_override() {
  local shortname="$1"
  local varname="PROJECT_REPO_$(echo "$shortname" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
  if [ -f "$LOCAL_OVERRIDES" ]; then
    grep "^${varname}=" "$LOCAL_OVERRIDES" 2>/dev/null | head -1 | cut -d'=' -f2- | tr -d '"' || true
  fi
}

# --- find ---
find_repo() {
  local shortname="$1"
  local github_repo="$2"

  # Local override wins
  local override
  override=$(get_local_override "$shortname")
  if [ -n "$override" ] && [ -d "$override" ]; then
    echo "$override"
    return 0
  fi

  # Search known paths by directory name
  for search_dir in $SEARCH_PATHS; do
    local candidate="$search_dir/$github_repo"
    if [ -d "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done

  # Deep scan: match on git remote
  if [ "$DEEP_SCAN" = true ]; then
    for search_dir in $SEARCH_PATHS; do
      [ ! -d "$search_dir" ] && continue
      while IFS= read -r git_dir; do
        local repo_dir
        repo_dir=$(dirname "$git_dir")
        local remote
        remote=$(git -C "$repo_dir" remote get-url origin 2>/dev/null || true)
        if echo "$remote" | grep -q "/$github_repo\(\.git\)\?\$"; then
          echo "$repo_dir"
          return 0
        fi
      done < <(find "$search_dir" -maxdepth 3 -name ".git" -type d 2>/dev/null)
    done
  fi

  return 1
}

# --- parse repos.conf ---
SHORTNAMES=()
GITHUB_REPOS=()
PROJECT_FILES=()
ICONS=()
TECHS=()
BRANCHES=()
JIRAS=()
BUILDS=()
PATHS=()

while IFS='|' read -r shortname github_repo project_file icon tech base_branch jira_prefix build_tool; do
  case "$shortname" in \#*|"") continue ;; esac
  shortname=$(echo "$shortname" | xargs)
  github_repo=$(echo "$github_repo" | xargs)

  SHORTNAMES+=("$shortname")
  GITHUB_REPOS+=("$github_repo")
  PROJECT_FILES+=("$(echo "$project_file" | xargs)")
  ICONS+=("$(echo "$icon" | xargs)")
  TECHS+=("$(echo "$tech" | xargs)")
  BRANCHES+=("$(echo "$base_branch" | xargs)")
  JIRAS+=("$(echo "$jira_prefix" | xargs)")
  BUILDS+=("$(echo "$build_tool" | xargs)")

  local_path=$(find_repo "$shortname" "$github_repo" || true)
  PATHS+=("$local_path")
done < "$REPOS_CONF"

# --- write env file ---
mkdir -p "$CLAUDE_DIR"
{
  echo "# Auto-generated by claude-toolkit/scripts/discover-repos.sh"
  echo "# Re-run ./install.sh or scripts/discover-repos.sh to refresh."
  echo "# Override paths in ~/.claude/project-repos.local.env"
  echo "#"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  for i in "${!SHORTNAMES[@]}"; do
    varname="PROJECT_REPO_$(echo "${SHORTNAMES[$i]}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
    if [ -n "${PATHS[$i]}" ]; then
      echo "${varname}=\"${PATHS[$i]}\""
    else
      echo "# ${varname}=  # not found"
    fi
  done
} > "$ENV_FILE"

# --- write JSON file ---
{
  echo "{"
  echo "  \"_generated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\","
  echo "  \"_note\": \"Auto-generated by claude-toolkit. Re-run ./install.sh to refresh.\","
  echo "  \"repos\": {"
  first=true
  for i in "${!SHORTNAMES[@]}"; do
    [ "$first" = true ] && first=false || echo ","
    path="${PATHS[$i]}"
    printf '    "%s": {\n' "${SHORTNAMES[$i]}"
    printf '      "github_repo": "%s/%s",\n' "$GITHUB_OWNER_DEFAULT" "${GITHUB_REPOS[$i]}"
    if [ -n "$path" ]; then
      printf '      "path": "%s",\n' "$path"
    else
      printf '      "path": null,\n'
    fi
    printf '      "tech": "%s",\n' "${TECHS[$i]}"
    printf '      "base_branch": "%s",\n' "${BRANCHES[$i]}"
    printf '      "jira_prefix": "%s",\n' "${JIRAS[$i]}"
    printf '      "build_tool": "%s",\n' "${BUILDS[$i]}"
    printf '      "icon": "%s",\n' "${ICONS[$i]}"
    if [ -n "${PROJECT_FILES[$i]}" ]; then
      printf '      "has_project_instructions": true\n'
    else
      printf '      "has_project_instructions": false\n'
    fi
    printf '    }'
  done
  echo ""
  echo "  }"
  echo "}"
} > "$JSON_FILE"

# --- report ---
FOUND=0
TOTAL=${#SHORTNAMES[@]}
for i in "${!SHORTNAMES[@]}"; do
  [ -n "${PATHS[$i]}" ] && FOUND=$((FOUND + 1))
done

echo "Discovered $FOUND/$TOTAL repos"
echo "  Env:  $ENV_FILE"
echo "  JSON: $JSON_FILE"

if [ $FOUND -lt $TOTAL ]; then
  echo ""
  echo "Missing repos (not found in search paths):"
  for i in "${!SHORTNAMES[@]}"; do
    if [ -z "${PATHS[$i]}" ]; then
      echo "  - ${SHORTNAMES[$i]} (${GITHUB_REPOS[$i]})"
    fi
  done
  echo ""
  echo "To fix: clone the repo, set PROJECT_REPOS_DIR, or add overrides to"
  echo "  $LOCAL_OVERRIDES"
  echo "Example:"
  echo "  PROJECT_REPO_API=/path/to/my/api-repo"
fi
